#!/bin/bash
# This is a simple post deploy hook executed after your application
# is deployed and started.  This script gets executed directly, so
# it could be python, php, ruby, etc.

#execute init only for the fist time
source $OPENSHIFT_HOMEDIR'python/virtenv/bin/activate'
CURRENT_DIRECTORY=$(pwd)

echo "Entering  $OPENSHIFT_REPO_DIR'wsgi/'"
cd $OPENSHIFT_REPO_DIR'wsgi/'
if [ ! -d $OPENSHIFT_REPO_DIR'wsgi/migrations/' ]; then
    echo "Executing 'python db.py' db init"
    python db.py db init
fi

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/db.py' db migrate'"
python db.py db migrate

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/db.py' db upgrade"
python db.py db upgrade

echo "Operations executed entering $CURRENT_DIRECTORY"
cd $CURRENT_DIRECTORY